# This is a basic workflow to help you get started with Actions

name: Build Thesis PDF

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: 
  pull_request:
    branches: [master]
  push:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-thesis:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@master
      - name: Append date to pdf
        run: |
            date="$(date +%Y_%m_%d-%Hh%Mm%Ss)";
            file="thesis_payen.${date}.pdf";
            cp build/thesis_payen.pdf ${file};
      - name: Upload Latex PDF
        uses: actions/upload-artifact@v2
        with:
          name: thesis_payen
          path: thesis_payen.*.pdf
      - name: Upload build dir
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: build_dir
          path: build/
